### ISSUE TITLE
'All' option on Filters

### ISSUE THREAD

**Issue by mariomarine** [mariomarine/nordicNumbers#52]
So we had a request for the ability to add the option 'All' to the dropdowns in the Filter Component (aka, you can choose 'All', 'Boys', or 'Girls' when picking a Gender).

**Comment by schillingjerrid** [comment]
@mariomarine 
- Would you like this added to all of the filters (i.e. Gender, Skill, Season)?
- Should the 'All' option be the default option of each filter?
- Would it be better to have the 'All' option have the text of 'All' and the value of 'All' or should it be a null value and display nothing?

**Comment by rbuchmeier** [comment]
@schillingjerrid 
I like the first two for sure.
I think the "All" option would be easier to read if it said "All" and had the value "All".
